spring:
  application:
    name: velogclone
  datasource:
    url: jdbc:mysql://localhost:3306/velogdb
    username: yubin
    password: yubin1203
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080